### ISSUE TITLE
problem with install

### ISSUE THREAD

**Issue by Cataphract89** [Notifysolutions/request_curl#5]
I have a problem with the "pip install request_curl". Python version 3.10. When I try to install - I get the following error:

> Collecting pycurl<8.0.0,>=7.45.2
> Using cached pycurl-7.45.2.tar.gz (234 kB)
> Preparing metadata (setup.py) ... error
> error: subprocess-exited-with-error

>   × python setup.py egg_info did not run successfully.
>   │ exit code: 10
>   ╰─> [1 lines of output]
>       Please specify --curl-dir=/path/to/built/libcurl
>       [end of output]
> 

>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: metadata-generation-failed

What could be the problem?

**Comment by h3adex** [comment]
Hi,

It seems that you are encountering an error while installing pycurl on your system. In order to use or build pycurl, you will need to have libcurl installed on your system.

To resolve this issue, you may want to refer to the official pycurl documentation, which provides detailed instructions on how to install pycurl on various platforms. Here's the link to the installation section of the documentation: http://pycurl.io/docs/latest/index.html#installation.

Alternatively, you can use our pre-built Docker image which includes libcurl, making the installation process easier. You can find the instructions on how to use the Docker image here: https://github.com/Notifysolutions/request_curl#usage-with-curl-impersonate.

I hope this information is helpful in resolving your issue.
